# Generated by Django 2.2.9 on 2022-08-19 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmsslider',
            old_name='cms2_img',
            new_name='cms_img',
        ),
    ]
