# Generated by Django 2.2.9 on 2022-08-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20220825_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_img',
            field=models.ImageField(upload_to='sliderimg/'),
        ),
    ]
