# Generated by Django 4.1 on 2022-08-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20220825_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
